/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visitor;

import DBConnection.DB;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;


public class Home extends javax.swing.JFrame {

   
    public Home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setIcon();
        try{int g=0;
    
      
            Vector<String> header=new Vector<String>();
            
            header.add("Company_Name");
            
            Vector<Vector<String>> data=new Vector<Vector<String>>();
            DB db=new DB();
            db.stmt=db.con.createStatement();
            db.rst=db.stmt.executeQuery("select cname from companydet");

            while (db.rst.next())
            {g++;
                Vector<String> temp=new Vector<String>();
                temp.add(db.rst.getString(1));
                
                data.add(temp);
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(data,header));
selectcompany.setVisible(true);
jTable2.grabFocus();
db.close();
if(g==0)
{
    JOptionPane.showMessageDialog(this,"Please Check the Database Connection and try Again.!","Alert",JOptionPane.ERROR_MESSAGE);
}
        

        }
        catch(Exception e)
        {
            e.getMessage();
        }
        
                
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        selectcompany = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        login = new javax.swing.JInternalFrame();
        jPanel11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(320, 200, 595, 315));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray)));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selectcompany.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        selectcompany.setClosable(true);
        selectcompany.setTitle("Select Company");
        selectcompany.setVisible(false);
        selectcompany.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                selectcompanyInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        selectcompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                selectcompanyKeyPressed(evt);
            }
        });
        selectcompany.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel20.setText("Registered Companies");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 50));

        selectcompany.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 255), 1, true));
        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setCellSelectionEnabled(true);
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setRowHeight(22);
        jTable2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel10.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 700, 370));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setBorder(null);
        jPanel10.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 30, -1));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jTextField16.setForeground(new java.awt.Color(255, 255, 255));
        jTextField16.setBorder(null);
        jPanel10.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 30, -1));

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setBorder(null);
        jPanel10.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 30, -1));

        selectcompany.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 370));

        jPanel1.add(selectcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 700, 450));

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setClosable(true);
        login.setVisible(false);
        login.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                loginInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 153, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 26)); // NOI18N
        jLabel21.setText("Login Panel");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, -1));

        login.getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 50));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16MouseExited(evt);
            }
        });

        jPasswordField2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(51, 153, 255)));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel26.setText("      LOGIN");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel24.setText("Password:");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel23.setText("Username:");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 2, 1, new java.awt.Color(51, 153, 255)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel15MouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel27.setText("      CLEAR");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel27MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(15, 15, 15)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(7, 7, 7)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(247, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap(143, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        login.getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 450, 200));

        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 460, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visitor/Visitor + Front Image - Copy (2).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            int row=jTable2.getSelectedRow();
            String click=(jTable2.getModel().getValueAt(row, 0).toString());
            DB db=new DB();
            String sql="select cid,uname,pswd from companydet where cname='"+click+"'";
            db.pstmt=db.con.prepareStatement(sql);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
                String add1=db.rst.getString("cid");
                jTextField17.setText(add1);
                String add2=db.rst.getString("uname");
                jTextField15.setText(add2);
                String add3=db.rst.getString("pswd");
                jTextField16.setText(add3);
 selectcompany.setVisible(false);
                login.setVisible(true);
                jTextField1.grabFocus();
            }
        db.close();} catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            try {
            int row=jTable2.getSelectedRow();
            String click=(jTable2.getModel().getValueAt(row, 0).toString());
            DB db=new DB();
            String sql="select cid,uname,pswd from companydet where cname='"+click+"'";
            db.pstmt=db.con.prepareStatement(sql);
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
                String add1=db.rst.getString("cid");
                jTextField17.setText(add1);
                String add2=db.rst.getString("uname");
                jTextField15.setText(add2);
                String add3=db.rst.getString("pswd");
                jTextField16.setText(add3);
                selectcompany.setVisible(false);
                login.setVisible(true);
                jTextField1.grabFocus();
            }
        db.close();} catch (Exception e) {
        }}      // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyPressed

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
                // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyReleased

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        try {
        String fy=jTextField16.getText();
            String usr=jTextField1.getText();
            String psw=new String(jPasswordField2.getPassword());
            String id=jTextField17.getText();
            String name=jTextField15.getText();    
        DB db=new DB();
        db.pstmt=db.con.prepareStatement("select * from useracc where cid='"+id+"' and uname='"+usr+"' and pswd='"+psw+"'");
        db.rst=db.pstmt.executeQuery();
        if(db.rst.next())
        {
            String ogname=db.rst.getString("ogname");
            String l="yes";
                        Main t=new Main(id,ogname);
                        t.setVisible(true);
                       db.close(); 
                        this.setVisible(false);
        }
        else
        {
        DB db1=new DB();
        db1.pstmt=db1.con.prepareStatement("select * from companydet where cid='"+id+"' and uname='"+usr+"' and pswd='"+psw+"'");
        db1.rst=db1.pstmt.executeQuery();
        if(db1.rst.next())
        {
            String l="yes";
                        Main t=new Main(id,"");
                        t.setVisible(true);
                       db.close();
                        this.setVisible(false);
        }else
        {
          JOptionPane.showMessageDialog(this,"Access Denied.! ","Alert",JOptionPane.ERROR_MESSAGE);
        }
        }
        } catch (Exception e) {
        e.printStackTrace();
        }
            
        
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        jPanel14.setBackground(new Color(0,153,255));
        jLabel26.setForeground(Color.white);
        
        /*try {
            String fy=jTextField16.getText();
            String usr=jTextField1.getText();
            String psw=new String(jPasswordField2.getPassword());
            String id=jTextField17.getText();
            String name=jTextField15.getText();
            DB db1=new DB();
            db1.pstmt=db1.con.prepareStatement("select ogname,uname,pswd,cid from useracc where cid='"+id+"'");
            db1.rst=db1.pstmt.executeQuery();
            if(db1.rst.next())
            {
                String ogname=db1.rst.getString(1);
                String usrd=db1.rst.getString(2);
                String pswd=db1.rst.getString(3);
                String ccid=db1.rst.getString(4);
                if(ccid.equals(id))
                {
                if(usr.equals(usrd))
                {
                    if(psw.equals(pswd))
                    {
                        String l="yes";
                        Main t=new Main(id,ogname);
                        t.setVisible(true);
                       db1.close(); 
                        this.setVisible(false);
                    }
                    else
                    {
                      db1.close();  
                        DB db=new DB();
            db.pstmt=db.con.prepareStatement("select uname,pswd from companydet where cid='"+id+"'");
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {  
                String usrd1=db.rst.getString(1);
                String pswd1=db.rst.getString(2);
                if(usr.equals(usrd1))
                {
                    if(psw.equals(pswd1))
                    {
                        String l="yes";
                        Main t=new Main(id,"");
                        t.setVisible(true);
                        
                       db.close();
                        this.setVisible(false);
                    }
                    else
                    { db.close();   
                        JOptionPane.showMessageDialog(this,"Access Denied.! Incorrect Password","Alert",JOptionPane.ERROR_MESSAGE);
                    }
                }else
                { db.close(); 
                    JOptionPane.showMessageDialog(this,"Invalid Username","Alert",JOptionPane.ERROR_MESSAGE);
                }
            }
                    }
                }else
                { db1.close(); 
                  DB db=new DB();
            db.pstmt=db.con.prepareStatement("select uname,pswd from companydet where cid='"+id+"'");
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
                String usrd2=db.rst.getString(1);
                String pswd2=db.rst.getString(2);
                if(usr.equals(usrd2))
                {
                    if(psw.equals(pswd2))
                    {
                        String l="yes";
                        Main t=new Main(id,"");
                        t.setVisible(true);
                       db.close(); 
                        this.setVisible(false);
                    }
                    else
                    { db.close(); 
                        JOptionPane.showMessageDialog(this,"Access Denied.! Incorrect Password","Alert",JOptionPane.ERROR_MESSAGE);
                    }
                }else
                { db.close(); 
                    JOptionPane.showMessageDialog(this,"Invalid Username","Alert",JOptionPane.ERROR_MESSAGE);
                }
            }
                }
            }
                else
                { db1.close(); 
              
                    JOptionPane.showMessageDialog(this,"You are not eligible for selected Company ","Alert",JOptionPane.ERROR_MESSAGE);
                }
            }else
            { db1.close();
             
            DB db=new DB();
            db.pstmt=db.con.prepareStatement("select uname,pswd from companydet where cid='"+id+"'");
            db.rst=db.pstmt.executeQuery();
            if(db.rst.next())
            {
                String usrd=db.rst.getString(1);
                String pswd=db.rst.getString(2);
                if(usr.equals(usrd))
                {
                    if(psw.equals(pswd))
                    {
                        String l="yes";
                        Main t=new Main(id,"");
                        t.setVisible(true);
                        db.close();
                        this.setVisible(false);
                    }
                    else
                    { db.close(); 
                        JOptionPane.showMessageDialog(this,"Access Denied.! Incorrect Password","Alert",JOptionPane.ERROR_MESSAGE);
                    }
                }else
                {db.close();
                    JOptionPane.showMessageDialog(this,"Invalid Username","Alert",JOptionPane.ERROR_MESSAGE);
          db.close();
                db1.close();}
           db.close(); }
        db.close();}}
        catch (Exception e) {
 e.printStackTrace();
        }
*/
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        jPanel14.setBackground(Color.white);
        jLabel26.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jLabel26MouseExited

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
    
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        jPanel14.setBackground(new Color(153,153,255));
        jLabel26.setForeground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        jPanel14.setBackground(Color.white);
        jLabel26.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel14MouseExited

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        jTextField1.setText("");
        jPasswordField2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseEntered
        jPanel15.setBackground(new Color(0,153,255));
        jLabel27.setForeground(Color.white);
    }//GEN-LAST:event_jLabel27MouseEntered

    private void jLabel27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseExited
        jPanel15.setBackground(Color.white);
        jLabel27.setForeground(new Color(0,0,0));// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseExited

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        jTextField1.setText("");
        jPasswordField2.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseEntered
        jPanel15.setBackground(new Color(153,153,255));
        jLabel27.setForeground(Color.white);
    }//GEN-LAST:event_jPanel15MouseEntered

    private void jPanel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseExited
        jPanel15.setBackground(Color.white);
        jLabel27.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jPanel15MouseExited

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
              try {
        String fy=jTextField16.getText();
            String usr=jTextField1.getText();
            String psw=new String(jPasswordField2.getPassword());
            String id=jTextField17.getText();
            String name=jTextField15.getText();    
        DB db=new DB();
        db.pstmt=db.con.prepareStatement("select * from useracc where cid='"+id+"' and uname='"+usr+"' and pswd='"+psw+"'");
        db.rst=db.pstmt.executeQuery();
        if(db.rst.next())
        {
            String ogname=db.rst.getString("ogname");
            String l="yes";
                        Main t=new Main(id,ogname);
                        t.setVisible(true);
                       db.close(); 
                        this.setVisible(false);
                        
        }
        else
        {
          db.close();  
        DB db1=new DB();
        db1.pstmt=db1.con.prepareStatement("select * from companydet where cid='"+id+"' and uname='"+usr+"' and pswd='"+psw+"'");
        db1.rst=db1.pstmt.executeQuery();
        if(db1.rst.next())
        {
            String l="yes";
                        Main t=new Main(id,"");
                        t.setVisible(true);
                       db1.close();
                        this.setVisible(false);
        }else
        {db.close();
          JOptionPane.showMessageDialog(this,"Access Denied.! ","Alert",JOptionPane.ERROR_MESSAGE);
        }
        }
        } catch (Exception e) {
        e.printStackTrace();
        }
      
        }
        if(evt.getKeyCode()==KeyEvent.VK_UP)
{
    jTextField1.grabFocus();
}
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
    jPasswordField2.grabFocus();
}
if(evt.getKeyCode()==KeyEvent.VK_DOWN)
{
    jPasswordField2.grabFocus();
}// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void selectcompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_selectcompanyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectcompanyKeyPressed

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseEntered

    private void jPanel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseExited

    private void selectcompanyInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_selectcompanyInternalFrameClosing
      new Home1().setVisible(true);
      this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_selectcompanyInternalFrameClosing

    private void loginInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_loginInternalFrameClosing
      selectcompany.setVisible(true);
      // TODO add your handling code here:
    }//GEN-LAST:event_loginInternalFrameClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JInternalFrame login;
    private javax.swing.JInternalFrame selectcompany;
    // End of variables declaration//GEN-END:variables
  private void setIcon() {
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("tndsvjwewpsbdkwnwbbn.png")));
    }
}
